//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int ID { get; set; }
        public int LessonID { get; set; }
        public string Title { get; set; }
        public int UserID { get; set; }
        public int Result { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual User User { get; set; }
    }
}
