//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutorial
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfAddition { get; set; }
        public string UrlPath { get; set; }
        public int LessonId { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
